/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-03-20 20:37:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.*;
import java.sql.*;
import java.time.Period;

public final class UserTaskList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Dhanush/Desktop/Zoho%20Mini-Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ToDo_List/WEB-INF/lib/struts-taglib-1.3.10.jar!/META-INF/tld/struts-html.tld", Long.valueOf(1227898810000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.10.jar", Long.valueOf(1615889409929L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.Period");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fform_0026_005fmethod_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ferrors_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fsubmit_0026_005fvalue_005fstyleClass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fmethod_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ferrors_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fsubmit_0026_005fvalue_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fmethod_005faction.release();
    _005fjspx_005ftagPool_005fhtml_005ferrors_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005fsubmit_0026_005fvalue_005fstyleClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("myList.jsp\r\n");
      out.write("\r\n");
      out.write("java version \"1.8.0_45\"\r\n");
      out.write("\r\n");
      out.write("Created By Dhanush L\r\n");
      out.write("                 \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>To-Do</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"icon\" href=\"resources/appIcon.png\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles/myList.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"scripts/myList.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	ServletContext context = request.getSession().getServletContext();
	String currUser = (String) context.getAttribute("currUser");
	int userId=-1, taskStatus, count=0, taskId=-1, importantStatus, flaggedStatus;
	String taskName="", description="";
	Date dateAdded;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-dark\" style=\"background-image: linear-gradient(-225deg, #FFAB91 50%, #78909C 50%)\">\r\n");
      out.write("\t\t<span style=\"font-size:30px; color: #818181; cursor:pointer\" onclick=\"openNav()\">&#9776;</span><br>\r\n");
      out.write("\t\t<div class=\"emailId\" id=\"emailId\">\r\n");
      out.write("    \t\t<a href=\"#\" class=\"navbar-brand\">");
      out.print(currUser);
      out.write("</a>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("    \t\t<li><a href=\"#\" class=\"nav-link\">Welcome</a></li>\r\n");
      out.write("    \t</ul>\r\n");
      out.write("\t\t<ul class=\"navbar-nav navbar-collapse justify-content-end\">\r\n");
      out.write("\t\t\t<li><a href=\"/ToDo_List/sign_in.jsp\" class=\"nav-link\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("  <br><br><br><br><br>\r\n");
      out.write("  <a href=\"#\">All Tasks</a>\r\n");
      out.write("  <a href=\"#\">Important Tasks</a>\r\n");
      out.write("  <a href=\"#\">Flagged Tasks</a>\r\n");
      out.write("  <a href=\"#\">Planned</a>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div class=\"container1\" id=\"container1\">\r\n");
      out.write("\t\t\t<h1>All Tasks</h1>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p><button class=\"w3-button w3-xlarge w3-circle w3-card-4\" style=\"background-color:#818181;\" id=\"myBtn\">+</button>  Add Task...</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"taskDiv\">\r\n");
      out.write("\t\t\t<div class=\"chunkedComponentList sticky\">\r\n");
      out.write("\t\t\t<div class=\"chunkedScrollContainer\">\r\n");
      out.write("\t\t\t");

				JDBC_List_Operations jdbc = new JDBC_List_Operations();
				Connection conn = jdbc.getConnection();
				
				userId = jdbc.getUserId(currUser);
				
				try{
					
					String sql = "SELECT task_id_table.task_id, task_name, description, date_added, task_status, important_status, flagged_status "+
								 "FROM task_id_table "+
								 "INNER JOIN tasks_table ON "+
						    	 "(task_id_table.user_id=? AND task_id_table.task_id=tasks_table.task_id) "+
								 "ORDER BY date_added ASC";
					
					PreparedStatement stmt = conn.prepareStatement(sql);
					stmt.setInt(1, userId);
					ResultSet rs = stmt.executeQuery();
					while (rs.next()){
						count++;
						taskId = rs.getInt("task_id");
						taskName = rs.getString("task_name");
						description = rs.getString("description");
						dateAdded = rs.getDate("date_added");
						taskStatus = rs.getInt("task_status");
						importantStatus = rs.getInt("important_status");
						flaggedStatus = rs.getInt("flagged_status");
						
						ResultSet rs1, rs2, rs3;
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div role=\"none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"taskItem\">\r\n");
      out.write("\t\t\t\t\t<div class=\"taskItem-body\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t");

						if(taskStatus==1){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"round\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"statusChk");
      out.print(count);
      out.write("\" value=\"on\" checked disabled/>\r\n");
      out.write("   \t\t\t\t\t\t\t <label for=\"statusChk");
      out.print(count);
      out.write("\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
	
						}else{ 
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"round\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"statusChk");
      out.print(count);
      out.write("\" value=\"off\" disabled/>\r\n");
      out.write("   \t\t\t\t\t\t\t <label for=\"statusChk");
      out.print(count);
      out.write("\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t");
 
						}
			
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<button tabindex=\"0\" class=\"taskItem-titleWrapper\" id=\"taskBtn");
      out.print(count);
      out.write("\" onclick=\"updateTask(this.id)\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"taskItem-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span style=\"font-weight:bold; color:#3F51B5; font-size:135%\" id=\"taskNameSpan");
      out.print(count);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(taskName);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"taskDateSpan");
      out.print(count);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t| Created on ");
      out.print(dateAdded);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span id=\"taskIdSpan");
      out.print(count);
      out.write("\" style=\"visibility:hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(taskId);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"metaDataInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"metaDataInfo-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"font-size:70%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(description);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"metaDataInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"metaDataInfo-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"font-size:70%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(description);
      out.write(' ');
      out.print(description);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t");

						if(importantStatus==1){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:45px; margin-top:5px; margin-left:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"important\" type=\"checkbox\" id=\"impStatusShow");
      out.print(count);
      out.write("\" value=\"on\" checked disabled/>\r\n");
      out.write("   \t\t\t\t\t\t\t <label class=\"importantlabelShow\" for=\"impStatusShow");
      out.print(count);
      out.write("\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t");

						}else{
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:45px; margin-top:5px; margin-left:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"important\" type=\"checkbox\" id=\"impStatusShow");
      out.print(count);
      out.write("\" value=\"off\" disabled/>\r\n");
      out.write("   \t\t\t\t\t\t\t <label class=\"importantlabelShow\" for=\"impStatusShow");
      out.print(count);
      out.write("\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t");

						}
						if(flaggedStatus==1){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:45px; margin-left:-30px; margin-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"important\" type=\"checkbox\" id=\"flagStatusShow");
      out.print(count);
      out.write("\" value=\"on\" checked disabled/>\r\n");
      out.write("   \t\t\t\t\t\t\t <label class=\"importantlabelShow2\" for=\"flagStatusShow");
      out.print(count);
      out.write("\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t");

						}else{
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-right:45px; margin-left:-30px; margin-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"important\" type=\"checkbox\" id=\"flagStatusShow");
      out.print(count);
      out.write("\" value=\"off\" disabled/>\r\n");
      out.write("   \t\t\t\t\t\t\t<label class=\"importantlabelShow2\" for=\"flagStatusShow");
      out.print(count);
      out.write("\"></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

						}
			
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t");

					}
					rs.close();
					conn.close();
				}catch(Exception e){
					System.out.println(e);
				}
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container2\">\r\n");
      out.write("\t\t\t<div class=\"details\">\r\n");
      out.write("\t\t\t\t<div data-is-scrollable=\"true\" class=\"details-body\">\r\n");
      out.write("\t\t\t\t\t<form action=\"updatingTasks.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"userId\" value=\"");
      out.print(userId);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" style=\"visibility:hidden\" name=\"taskId\" id=\"taskId\" required/>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"detailHeader\" style=\"border-radius:10px; margin-top:-25px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"detailHeader-titleWrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"round\" style=\"margin-top:-10px;margin-left:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"taskStatus\" id=\"taskStatus\"/>\r\n");
      out.write("   \t\t\t\t\t\t\t \t<label for=\"taskStatus\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"detailHeader-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-input2\" style=\"width:175px;\" id=\"taskNameF\" name=\"taskNameF\" readonly/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-right:45px; margin-top:5px; margin-left:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"important\" type=\"checkbox\" name=\"importantFlag\" id=\"impStatus\"/>\r\n");
      out.write("   \t\t\t\t\t\t\t \t<label class=\"importantlabel\" for=\"impStatus\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"margin-right:45px; margin-left:-30px; margin-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"important\" type=\"checkbox\" name=\"flaggedFlag\" id=\"flagStatus\"/>\r\n");
      out.write("   \t\t\t\t\t\t\t \t<label class=\"importantlabel2\" for=\"flagStatus\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \t<div class=\"input-container\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-plus icon\"></i>\r\n");
      out.write("                        \t\t<input type=\"text\" class=\"form-input2\" style=\"width:300px;\" id=\"subTasks\" name=\"subTasks\"/>\r\n");
      out.write("                        \t</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"detailHeader\" style=\"border-radius:10px;\">\r\n");
      out.write("                        \t<div class=\"input-container\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-bell icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\"  class=\"form-input2\" onfocus=\"(this.type='date')\" onblur=\"(this.type='text')\" style=\"width:300px;\" id=\"remainder\" name=\"remainder\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-calendar icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-input2\" onfocus=\"(this.type='date')\" onblur=\"(this.type='text')\" style=\"width:300px;\" id=\"dueDate\" name=\"dueDate\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-repeat icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-input2\" style=\"width:300px;\" id=\"repeat\" name=\"repeat\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"detailHeader\" style=\"border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-container\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-tags icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-input2\" style=\"height:40px;width:300px;\" id=\"category\" name=\"category\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t <br>\r\n");
      out.write("\t\t\t\t\t\t <div class=\"detailHeader\" style=\"border-radius:10px;\">\r\n");
      out.write("\t\t\t\t\t\t \t<div class=\"input-container\">\r\n");
      out.write("                        \t\t<i class=\"fa fa-info-circle icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-input2\" style=\"height:60px;border-radius:0px;width:300px;\" id=\"descriptionF\" name=\"descriptionF\"/>\r\n");
      out.write("\t\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"detailHeader-titleWrapper\" style=\"text-align:center\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class=\"sign-up button1\" value=\"Update\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"myModal\" class=\"w3-modal\">\r\n");
      out.write("  \t<!-- Modal content -->\r\n");
      out.write("  \t<div class=\"w3-modal-content w3-animate-top w3-card-4\">\r\n");
      out.write("    \t\t<span class=\"close\"></span>\r\n");
      out.write("      \t\t<div class=\"field-set\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_html_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:form
    org.apache.struts.taglib.html.FormTag _jspx_th_html_005fform_005f0 = (org.apache.struts.taglib.html.FormTag) _005fjspx_005ftagPool_005fhtml_005fform_0026_005fmethod_005faction.get(org.apache.struts.taglib.html.FormTag.class);
    boolean _jspx_th_html_005fform_005f0_reused = false;
    try {
      _jspx_th_html_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fform_005f0.setParent(null);
      // /UserTaskList.jsp(285,4) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setAction("adding");
      // /UserTaskList.jsp(285,4) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setMethod("post");
      int _jspx_eval_html_005fform_005f0 = _jspx_th_html_005fform_005f0.doStartTag();
      if (_jspx_eval_html_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_html_005ferrors_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("<br>\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_html_005ftext_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("<br>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_html_005ftext_005f1(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("<br>\r\n");
          out.write("\t\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_html_005fsubmit_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_html_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_html_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fform_0026_005fmethod_005faction.reuse(_jspx_th_html_005fform_005f0);
      _jspx_th_html_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ferrors_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:errors
    org.apache.struts.taglib.html.ErrorsTag _jspx_th_html_005ferrors_005f0 = (org.apache.struts.taglib.html.ErrorsTag) _005fjspx_005ftagPool_005fhtml_005ferrors_0026_005fproperty_005fnobody.get(org.apache.struts.taglib.html.ErrorsTag.class);
    boolean _jspx_th_html_005ferrors_005f0_reused = false;
    try {
      _jspx_th_html_005ferrors_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /UserTaskList.jsp(287,5) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ferrors_005f0.setProperty("taskname_e");
      int _jspx_eval_html_005ferrors_005f0 = _jspx_th_html_005ferrors_005f0.doStartTag();
      if (_jspx_th_html_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ferrors_0026_005fproperty_005fnobody.reuse(_jspx_th_html_005ferrors_005f0);
      _jspx_th_html_005ferrors_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ferrors_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f0 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f0_reused = false;
    try {
      _jspx_th_html_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /UserTaskList.jsp(288,5) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleClass("form-input1");
      // /UserTaskList.jsp(288,5) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setProperty("taskName");
      // /UserTaskList.jsp(288,5) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleId("taskName");
      int _jspx_eval_html_005ftext_005f0 = _jspx_th_html_005ftext_005f0.doStartTag();
      if (_jspx_th_html_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.reuse(_jspx_th_html_005ftext_005f0);
      _jspx_th_html_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f1 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f1_reused = false;
    try {
      _jspx_th_html_005ftext_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /UserTaskList.jsp(291,5) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setStyleClass("form-input");
      // /UserTaskList.jsp(291,5) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setProperty("description");
      // /UserTaskList.jsp(291,5) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f1.setStyleId("description");
      int _jspx_eval_html_005ftext_005f1 = _jspx_th_html_005ftext_005f1.doStartTag();
      if (_jspx_th_html_005ftext_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.reuse(_jspx_th_html_005ftext_005f1);
      _jspx_th_html_005ftext_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f1, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fsubmit_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:submit
    org.apache.struts.taglib.html.SubmitTag _jspx_th_html_005fsubmit_005f0 = (org.apache.struts.taglib.html.SubmitTag) _005fjspx_005ftagPool_005fhtml_005fsubmit_0026_005fvalue_005fstyleClass_005fnobody.get(org.apache.struts.taglib.html.SubmitTag.class);
    boolean _jspx_th_html_005fsubmit_005f0_reused = false;
    try {
      _jspx_th_html_005fsubmit_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fsubmit_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /UserTaskList.jsp(294,5) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fsubmit_005f0.setStyleClass("sign-up button1");
      // /UserTaskList.jsp(294,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fsubmit_005f0.setValue("Add");
      int _jspx_eval_html_005fsubmit_005f0 = _jspx_th_html_005fsubmit_005f0.doStartTag();
      if (_jspx_th_html_005fsubmit_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fsubmit_0026_005fvalue_005fstyleClass_005fnobody.reuse(_jspx_th_html_005fsubmit_005f0);
      _jspx_th_html_005fsubmit_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fsubmit_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fsubmit_005f0_reused);
    }
    return false;
  }
}
